eFORMAT: 1A
HOST: http://api.mv2.domain/api/v2/

# Mv2 - Web

MV2 utilizes JWT Authentication which generates token on user sign in. Token is required for most requests.
Token can be send as `token` parameter as query string or as header in such format `Authorization: Bearer {system-generated-token}`.

When sending request with body of JSON headers should contain `Content-Type: application/json`.

## Group Authentication
## Sign In [/auth/login]
### Sign In [POST]
Attempt to login and get user token.
`token` is NOT required.

+ Request (application/json)

        {
            "email": "admin@super.com",
            "password": "password"
        }

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "userType": "admin",
                    "__DEVNODE__userType": "will be `admin` or `customer`",
                    "token": "your.generated.token",
                    "user": {
                        "id": 1,
                        "civility": "mr",
                        "lastName": "Lala",
                        "firstName": "Lulu",
                        "email": "luluz@mailinator.com",
                        "mobilePhone": null,
                        "officePhone": null,
                        "jobTitle": "CED",
                        "isAdmin": false,
                        "isActive": true,
                        "profilePicPath": null,
                        "company": {
                            "id": 1,
                            "fullName": "21 July Editz",
                            "tradeName": "1111",
                            "intercommunityVat": "11111",
                            "naf": "1111",
                            "siren": null,
                            "vat": null,
                            "vatOption": 1,
                            "raisonSociale": {
                                "id": 5,
                                "code": "M14",
                                "label": "EURL"
                            },
                            "address": {
                                "id": 1,
                                "address1": "S Las Vegas Blvd",
                                "address2": null,
                                "zipcode": "11",
                                "city": "Clark County",
                                "country": "United States",
                                "lat": 36.045999,
                                "lng": -115.1722248
                            }
                        },
                        "accesses": [
                            {
                                "id": 1,
                                "isPowerUser": true,
                                "customer": {
                                    "id": 1,
                                    "fullName": "21 July Editz",
                                    "tradeName": "1111",
                                    "vatOption": 1,
                                    "active": 0,
                                    "intercommunityVat": "11111",
                                    "vat": null,
                                    "siren": null,
                                    "naf": "1111",
                                    "iban": "FR7630001007941234567890185",
                                    "accountName": "21212",
                                    "swift": "FRFRFR76300",
                                    "addressOption": 1,
                                    "customerImg": [
                                        ""
                                    ],
                                    "company": {
                                        "id": 1,
                                        "fullName": "Tesla Corp",
                                        "tradeName": "Tesla",
                                        "intercommunityVat": "11111",
                                        "naf": "1111",
                                        "siren": null,
                                        "vat": null,
                                        "vatOption": 1,
                                        "raisonSociale": {
                                            "id": 5,
                                            "code": "M14",
                                            "label": "EURL"
                                        },
                                        "address": {
                                            "id": 1,
                                            "address1": "S Las Vegas Blvd",
                                            "address2": null,
                                            "zipcode": "11",
                                            "city": "Clark County",
                                            "country": "United States",
                                            "lat": 36.045999,
                                            "lng": -115.1722248
                                        }
                                    }
                                },
                                "resources": {
                                    "portfolios": [
                                        {
                                            "id": 1,
                                            "__DEVNOTE__id": "Id of portfolio",
                                            "profile": {
                                                "id": 3,
                                                "name": "Broker Portfolio 1",
                                                "slug": "1-broker-11231"
                                            },
                                            "allPropertiesOption": false,
                                            "properties": [
                                                {
                                                    "id": 1,
                                                    "name": "Property #1",
                                                    "__DEVNOTE_profile": "Profile here is User User Access.",
                                                    "profile": {
                                                        "id": 4,
                                                        "name": "Broker",
                                                        "slug": "1-broker-1524"
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "id": 2,
                                            "__DEVNOTE__id": "Id of portfolio",
                                            "profile": null,
                                            "allPropertiesOption": true,
                                            "__DEVNOTE_allPropertiesOption": "Property option used to override all property access.",
                                            "properties": null
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }

## Sign Out [/auth/logout]
### Sign Out [POST]
Logout and clear user token.
`token` is required.

+ Request (application/json)

        {
            "email": "admin@customer.com",
        }

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": 1
            }

## Reset Password [/auth/reset-password]
### Reset Password [POST]
Reset password.

+ Request (application/json)

        {
            "email": "admin@customer.com",
        }

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "email": "admin@customer.com"
                }
            }

## Group Admin: User
## Admin: User List [/admin/users?]
### (Admin) User List [GET]
User list.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 1,
                        "civility": "mr",
                        "lastName": "Lala",
                        "firstName": "Lulu",
                        "email": "luluz@mailinator.com",
                        "mobilePhone": null,
                        "officePhone": null,
                        "jobTitle": "CED",
                        "isAdmin": false,
                        "isActive": true,
                        "profilePicPath": null,
                        "company": {
                            "id": 1,
                            "fullName": "21 July Editz",
                            "tradeName": "1111",
                            "intercommunityVat": "11111",
                            "naf": "1111",
                            "siren": null,
                            "vat": null,
                            "vatOption": 1,
                            "raisonSociale": {
                                "id": 5,
                                "code": "M14",
                                "label": "EURL"
                            },
                            "address": {
                                "id": 1,
                                "address1": "S Las Vegas Blvd",
                                "address2": null,
                                "zipcode": "11",
                                "city": "Clark County",
                                "country": "United States",
                                "lat": 36.045999,
                                "lng": -115.1722248
                            }
                        },
                        "accesses": [
                            {
                                "id": 1,
                                "isPowerUser": true,
                                "customer": {
                                    "id": 1,
                                    "fullName": "21 July Editz",
                                    "tradeName": "1111",
                                    "vatOption": 1,
                                    "active": 0,
                                    "intercommunityVat": "11111",
                                    "vat": null,
                                    "siren": null,
                                    "naf": "1111",
                                    "iban": "FR7630001007941234567890185",
                                    "accountName": "21212",
                                    "swift": "FRFRFR76300",
                                    "addressOption": 1,
                                    "customerImg": [
                                        ""
                                    ],
                                    "company": {
                                        "id": 1,
                                        "fullName": "Tesla Corp",
                                        "tradeName": "Tesla",
                                        "intercommunityVat": "11111",
                                        "naf": "1111",
                                        "siren": null,
                                        "vat": null,
                                        "vatOption": 1,
                                        "raisonSociale": {
                                            "id": 5,
                                            "code": "M14",
                                            "label": "EURL"
                                        },
                                        "address": {
                                            "id": 1,
                                            "address1": "S Las Vegas Blvd",
                                            "address2": null,
                                            "zipcode": "11",
                                            "city": "Clark County",
                                            "country": "United States",
                                            "lat": 36.045999,
                                            "lng": -115.1722248
                                        }
                                    }
                                },
                                "resources": {
                                    "portfolios": [
                                        {
                                            "id": 1,
                                            "__DEVNOTE__id": "Id of portfolio",
                                            "profile": {
                                                "id": 3,
                                                "name": "Broker Portfolio 1",
                                                "slug": "1-broker-11231"
                                            },
                                            "allPropertiesOption": false,
                                            "properties": [
                                                {
                                                    "id": 1,
                                                    "name": "Property #1",
                                                    "__DEVNOTE_profile": "Profile here is User User Access.",
                                                    "profile": {
                                                        "id": 4,
                                                        "name": "Broker",
                                                        "slug": "1-broker-1524"
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "id": 2,
                                            "__DEVNOTE__id": "Id of portfolio",
                                            "profile": null,
                                            "allPropertiesOption": true,
                                            "__DEVNOTE_allPropertiesOption": "Property option used to override all property access.",
                                            "properties": null
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                ]
            }

## Admin: User Detail [/admin/users/{userId}?]
### (Admin) User Detail [GET]
User detail.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 1,
                    "civility": "mr",
                    "lastName": "Lala",
                    "firstName": "Lulu",
                    "email": "luluz@mailinator.com",
                    "mobilePhone": null,
                    "officePhone": null,
                    "jobTitle": "CED",
                    "isAdmin": false,
                    "isActive": true,
                    "profilePicPath": null,
                    "company": {
                        "id": 1,
                        "fullName": "21 July Editz",
                        "tradeName": "1111",
                        "intercommunityVat": "11111",
                        "naf": "1111",
                        "siren": null,
                        "vat": null,
                        "vatOption": 1,
                        "raisonSociale": {
                            "id": 5,
                            "code": "M14",
                            "label": "EURL"
                        },
                        "address": {
                            "id": 1,
                            "address1": "S Las Vegas Blvd",
                            "address2": null,
                            "zipcode": "11",
                            "city": "Clark County",
                            "country": "United States",
                            "lat": 36.045999,
                            "lng": -115.1722248
                        }
                    },
                    "accesses": [
                        {
                            "id": 1,
                            "isPowerUser": true,
                            "customer": {
                                "id": 1,
                                "fullName": "21 July Editz",
                                "tradeName": "1111",
                                "vatOption": 1,
                                "active": 0,
                                "intercommunityVat": "11111",
                                "vat": null,
                                "siren": null,
                                "naf": "1111",
                                "iban": "FR7630001007941234567890185",
                                "accountName": "21212",
                                "swift": "FRFRFR76300",
                                "addressOption": 1,
                                "customerImg": [
                                    ""
                                ],
                                "company": {
                                    "id": 1,
                                    "fullName": "Tesla Corp",
                                    "tradeName": "Tesla",
                                    "intercommunityVat": "11111",
                                    "naf": "1111",
                                    "siren": null,
                                    "vat": null,
                                    "vatOption": 1,
                                    "raisonSociale": {
                                        "id": 5,
                                        "code": "M14",
                                        "label": "EURL"
                                    },
                                    "address": {
                                        "id": 1,
                                        "address1": "S Las Vegas Blvd",
                                        "address2": null,
                                        "zipcode": "11",
                                        "city": "Clark County",
                                        "country": "United States",
                                        "lat": 36.045999,
                                        "lng": -115.1722248
                                    }
                                }
                            },
                            "resources": {
                                "portfolios": [
                                    {
                                        "id": 1,
                                        "__DEVNOTE__id": "Id of portfolio",
                                        "profile": {
                                            "id": 3,
                                            "name": "Broker Portfolio 1",
                                            "slug": "1-broker-11231"
                                        },
                                        "allPropertiesOption": false,
                                        "properties": [
                                            {
                                                "id": 1,
                                                "name": "Property #1",
                                                "__DEVNOTE_profile": "Profile here is User User Access.",
                                                "profile": {
                                                    "id": 4,
                                                    "name": "Broker",
                                                    "slug": "1-broker-1524"
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        "id": 2,
                                        "__DEVNOTE__id": "Id of portfolio",
                                        "profile": null,
                                        "allPropertiesOption": true,
                                        "__DEVNOTE_allPropertiesOption": "Property option used to override all property access.",
                                        "properties": null
                                    }
                                ]
                            }
                        }
                    ]
                }
            }

## Admin: User Create [/admin/users]
### (NOT AVAILABLE ATM)(Admin) User Create [POST]
Create user.

+ Request (application/json)

        {
            "civility": "mr",
            "lastName": "Lala",
            "firstName": "Lulu",
            "email": "luluz@mailinator.com",
            "mobilePhone": null,
            "officePhone": null,
            "jobTitle": "CED",
        
        
            "profilePicPath": null,
        
            "__DEVNOTE__company": "Can lookup or create",
            "company": {
                "id": 1,
                "fullName": "21 July Editz",
                "tradeName": "1111",
                "raisonSociale": {
                    "id": 5,
                    "code": "M14",
                    "label": "EURL"
                },
                "intercommunityVat": "11111",
                "naf": "1111",
                "siren": null,
                "vat": null,
                "vatOption": 1,
                "address": {
                    "id": 1,
                    "address1": "S Las Vegas Blvd",
                    "address2": null,
                    "zipcode": "11",
                    "city": "Clark County",
                    "country": "United States",
                    "lat": 36.045999,
                    "lng": -115.1722248
                }
            }
        }

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 1,
                    "civility": "mr",
                    "lastName": "Lala",
                    "firstName": "Lulu",
                    "email": "luluz@mailinator.com",
                    "mobilePhone": null,
                    "officePhone": null,
                    "jobTitle": "CED",
                    "isAdmin": false,
                    "isActive": true,
                    "profilePicPath": null,
                    "company": {
                        "id": 1,
                        "fullName": "21 July Editz",
                        "tradeName": "1111",
                        "intercommunityVat": "11111",
                        "naf": "1111",
                        "siren": null,
                        "vat": null,
                        "vatOption": 1,
                        "raisonSociale": {
                            "id": 5,
                            "code": "M14",
                            "label": "EURL"
                        },
                        "address": {
                            "id": 1,
                            "address1": "S Las Vegas Blvd",
                            "address2": null,
                            "zipcode": "11",
                            "city": "Clark County",
                            "country": "United States",
                            "lat": 36.045999,
                            "lng": -115.1722248
                        }
                    },
                    "accesses": [
                        {
                            "id": 1,
                            "isPowerUser": true,
                            "customer": {
                                "id": 1,
                                "fullName": "21 July Editz",
                                "tradeName": "1111",
                                "vatOption": 1,
                                "active": 0,
                                "intercommunityVat": "11111",
                                "vat": null,
                                "siren": null,
                                "naf": "1111",
                                "iban": "FR7630001007941234567890185",
                                "accountName": "21212",
                                "swift": "FRFRFR76300",
                                "addressOption": 1,
                                "customerImg": [
                                    ""
                                ],
                                "company": {
                                    "id": 1,
                                    "fullName": "Tesla Corp",
                                    "tradeName": "Tesla",
                                    "intercommunityVat": "11111",
                                    "naf": "1111",
                                    "siren": null,
                                    "vat": null,
                                    "vatOption": 1,
                                    "raisonSociale": {
                                        "id": 5,
                                        "code": "M14",
                                        "label": "EURL"
                                    },
                                    "address": {
                                        "id": 1,
                                        "address1": "S Las Vegas Blvd",
                                        "address2": null,
                                        "zipcode": "11",
                                        "city": "Clark County",
                                        "country": "United States",
                                        "lat": 36.045999,
                                        "lng": -115.1722248
                                    }
                                }
                            },
                            "resources": {
                                "portfolios": [
                                    {
                                        "id": 1,
                                        "__DEVNOTE__id": "Id of portfolio",
                                        "profile": {
                                            "id": 3,
                                            "name": "Broker Portfolio 1",
                                            "slug": "1-broker-11231"
                                        },
                                        "allPropertiesOption": false,
                                        "properties": [
                                            {
                                                "id": 1,
                                                "name": "Property #1",
                                                "__DEVNOTE_profile": "Profile here is User User Access.",
                                                "profile": {
                                                    "id": 4,
                                                    "name": "Broker",
                                                    "slug": "1-broker-1524"
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        "id": 2,
                                        "__DEVNOTE__id": "Id of portfolio",
                                        "profile": null,
                                        "allPropertiesOption": true,
                                        "__DEVNOTE_allPropertiesOption": "Property option used to override all property access.",
                                        "properties": null
                                    }
                                ]
                            }
                        }
                    ]
                }
            }

## Admin: User Update [/admin/users/{userId}]
### (NOT AVAILABLE ATM)(Admin) User Update [POST]

+ Request (application/json)

        {
            "id": 2,
            "civility": "mr",
            "lastName": "Lala",
            "firstName": "Lulu",
            "email": "luluz@mailinator.com",
            "mobilePhone": null,
            "officePhone": null,
            "jobTitle": "CED",
            
            "profilePicPath": null,
            
            "__DEVNOTE__company": "Can lookup or create; Id is required and if id is set, company data cannot be changed.",
            "company": {
                "id": 1,
                "fullName": "21 July Editz",
                "tradeName": "1111",
                "raisonSociale": {
                    "id": 5,
                    "code": "M14",
                    "label": "EURL"
                },
                "intercommunityVat": "11111",
                "naf": "1111",
                "siren": null,
                "vat": null,
                "vatOption": 1,
                "address": {
                    "id": 1,
                    "address1": "S Las Vegas Blvd",
                    "address2": null,
                    "zipcode": "11",
                    "city": "Clark County",
                    "country": "United States",
                    "lat": 36.045999,
                    "lng": -115.1722248
                }
            }
        }

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 1,
                    "civility": "mr",
                    "lastName": "Lala",
                    "firstName": "Lulu",
                    "email": "luluz@mailinator.com",
                    "mobilePhone": null,
                    "officePhone": null,
                    "jobTitle": "CED",
                    "isAdmin": false,
                    "isActive": true,
                    "profilePicPath": null,
                    "company": {
                        "id": 1,
                        "fullName": "21 July Editz",
                        "tradeName": "1111",
                        "intercommunityVat": "11111",
                        "naf": "1111",
                        "siren": null,
                        "vat": null,
                        "vatOption": 1,
                        "raisonSociale": {
                            "id": 5,
                            "code": "M14",
                            "label": "EURL"
                        },
                        "address": {
                            "id": 1,
                            "address1": "S Las Vegas Blvd",
                            "address2": null,
                            "zipcode": "11",
                            "city": "Clark County",
                            "country": "United States",
                            "lat": 36.045999,
                            "lng": -115.1722248
                        }
                    },
                    "accesses": [
                        {
                            "id": 1,
                            "isPowerUser": true,
                            "customer": {
                                "id": 1,
                                "fullName": "21 July Editz",
                                "tradeName": "1111",
                                "vatOption": 1,
                                "active": 0,
                                "intercommunityVat": "11111",
                                "vat": null,
                                "siren": null,
                                "naf": "1111",
                                "iban": "FR7630001007941234567890185",
                                "accountName": "21212",
                                "swift": "FRFRFR76300",
                                "addressOption": 1,
                                "customerImg": [
                                    ""
                                ],
                                "company": {
                                    "id": 1,
                                    "fullName": "Tesla Corp",
                                    "tradeName": "Tesla",
                                    "intercommunityVat": "11111",
                                    "naf": "1111",
                                    "siren": null,
                                    "vat": null,
                                    "vatOption": 1,
                                    "raisonSociale": {
                                        "id": 5,
                                        "code": "M14",
                                        "label": "EURL"
                                    },
                                    "address": {
                                        "id": 1,
                                        "address1": "S Las Vegas Blvd",
                                        "address2": null,
                                        "zipcode": "11",
                                        "city": "Clark County",
                                        "country": "United States",
                                        "lat": 36.045999,
                                        "lng": -115.1722248
                                    }
                                }
                            },
                            "resources": {
                                "portfolios": [
                                    {
                                        "id": 1,
                                        "__DEVNOTE__id": "Id of portfolio",
                                        "profile": {
                                            "id": 3,
                                            "name": "Broker Portfolio 1",
                                            "slug": "1-broker-11231"
                                        },
                                        "allPropertiesOption": false,
                                        "properties": [
                                            {
                                                "id": 1,
                                                "name": "Property #1",
                                                "__DEVNOTE_profile": "Profile here is User User Access.",
                                                "profile": {
                                                    "id": 4,
                                                    "name": "Broker",
                                                    "slug": "1-broker-1524"
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        "id": 2,
                                        "__DEVNOTE__id": "Id of portfolio",
                                        "profile": null,
                                        "allPropertiesOption": true,
                                        "__DEVNOTE_allPropertiesOption": "Property option used to override all property access.",
                                        "properties": null
                                    }
                                ]
                            }
                        }
                    ]
                }
            }


## Admin: User Delete [/admin/users/{userId}/delete]
### (NOT AVAILABLE ATM)(Admin) User Delete [POST]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": 1
            }

## Admin: User Impersonate [/admin/users/{userId}/impersonate]
### (Admin) User Impersonate [POST]
Login as selected User.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "userType": "admin",
                    "__DEVNODE__userType": "will be `admin` or `customer`",
                    
                    "token": "your.generated.token",
                    
                    "user": {
                        "id": 1,
                        "civility": "mr",
                        "lastName": "Lala",
                        "firstName": "Lulu",
                        "email": "luluz@mailinator.com",
                        "mobilePhone": null,
                        "officePhone": null,
                        "jobTitle": "CED",
                        "isAdmin": false,
                        "isActive": true,
                        "profilePicPath": null,
                        "company": {
                            "id": 1,
                            "fullName": "21 July Editz",
                            "tradeName": "1111",
                            "intercommunityVat": "11111",
                            "naf": "1111",
                            "siren": null,
                            "vat": null,
                            "vatOption": 1,
                            "raisonSociale": {
                                "id": 5,
                                "code": "M14",
                                "label": "EURL"
                            },
                            "address": {
                                "id": 1,
                                "address1": "S Las Vegas Blvd",
                                "address2": null,
                                "zipcode": "11",
                                "city": "Clark County",
                                "country": "United States",
                                "lat": 36.045999,
                                "lng": -115.1722248
                            }
                        },

                        "accesses": [
                            {
                                "id": 1,
                                "isPowerUser": false,

                                "__DEVNOTE__profile": "Profile object or NULL",
                                "profile": null,
                                
                                "__DEVNOTE__customer": "Customer object or NULL",
                                "customer": {
                                    "id": 1,
                                    "fullName": "21 July Editz",
                                    "tradeName": "1111",
                                    "vatOption": 1,
                                    "active": 0,
                                    "intercommunityVat": "11111",
                                    "vat": null,
                                    "siren": null,
                                    "naf": "1111",
                                    "iban": "FR7630001007941234567890185",
                                    "accountName": "21212",
                                    "swift": "FRFRFR76300",
                                    "addressOption": 1,
                                    "customerImg": [
                                        ""
                                    ],
                                    "company": {
                                        "id": 1,
                                        "fullName": "Tesla Corp",
                                        "tradeName": "Tesla",
                                        "intercommunityVat": "11111",
                                        "naf": "1111",
                                        "siren": null,
                                        "vat": null,
                                        "vatOption": 1,
                                        "raisonSociale": {
                                            "id": 5,
                                            "code": "M14",
                                            "label": "EURL"
                                        },
                                        "address": {
                                            "id": 1,
                                            "address1": "S Las Vegas Blvd",
                                            "address2": null,
                                            "zipcode": "11",
                                            "city": "Clark County",
                                            "country": "United States",
                                            "lat": 36.045999,
                                            "lng": -115.1722248
                                        }
                                    }
                                },
                                
                                "__DEVNOTE__resources": "Access/Permission Object or NULL",
                                "resources": null
                            }
                        ]
                    }
                }

## Admin: User Toggle Active [/admin/users/{userId}/toggle-active]
### (Admin) User Toggle Active [POST]
Toggle User Active Status.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "User Detail"
            }

## Admin: User Toggle Power User [/admin/users/{userId}/toggle-power-user]
### (Admin) User Toggle Power User [POST]
Toggle User Power User Status. Will be available on user with Company registered with valid Customer.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": "User Object"
            }

## Admin: User Reset Password [/admin/users/{userId}/reset-password]
### (Admin) User Reset Password [POST]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": "User Object"
            }

## Admin: User Customer List [/admin/users/{userId}/customers]
### (Admin) User Customer List [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 1,
                        "fullName": "Myre",
                        "tradeName": "Myre",
                        "vatOption": null,
                        "active": 1,
                        "intercommunityVat": null,
                        "vat": null,
                        "siren": null,
                        "naf": null,
                        "iban": null,
                        "accountName": null,
                        "swift": null,
                        "addressOption": 1,
                        "customerImg": [
                            ""
                        ],
                        "raisonSociale": {
                            "id": 1,
                            "code": "M01",
                            "label": "SOCIETE"
                        },
                        "company": {
                            "id": 1,
                            "address": {
                                "id": 1,
                                "address1": "4th Avenue Cafe",
                                "address2": "",
                                "zipcode": "14123",
                                "city": "Vancouver",
                                "country": "CANADA",
                                "lat": 49.2827291,
                                "lng": -123.1207375
                            },
                            "fullName": "Myre",
                            "tradeName": "Corp",
                            "raisonSociale": {
                                "id": 1,
                                "code": "M01",
                                "label": "SOCIETE"
                            },
                            "intercommunityVat": null,
                            "naf": null,
                            "siren": null,
                            "vat": null,
                            "vatOption": null
                        }
                    },
                    {
                        "id": 300,
                        "fullName": "Contech",
                        "tradeName": "Contech",
                        "vatOption": null,
                        "active": 1,
                        "intercommunityVat": null,
                        "vat": null,
                        "siren": null,
                        "naf": null,
                        "iban": null,
                        "accountName": null,
                        "swift": null,
                        "addressOption": 1,
                        "customerImg": [
                            ""
                        ],
                        "raisonSociale": {
                            "id": 1,
                            "code": "M01",
                            "label": "SOCIETE"
                        },
                        "company": {
                            "id": 300,
                            "address": {
                                "id": 1,
                                "address1": "4th Avenue Cafe",
                                "address2": "",
                                "zipcode": "14123",
                                "city": "Vancouver",
                                "country": "CANADA",
                                "lat": 49.2827291,
                                "lng": -123.1207375
                            },
                            "fullName": "Contect",
                            "tradeName": "Contect",
                            "raisonSociale": {
                                "id": 1,
                                "code": "M01",
                                "label": "SOCIETE"
                            },
                            "intercommunityVat": null,
                            "naf": null,
                            "siren": null,
                            "vat": null,
                            "vatOption": null
                        }
                    }
                ]
            }

## Admin: User Customer Power User Promote [/admin/users/{userId}/customers/{customerId}/promote]
### (Admin) User Customer Power User Promote [POST]
Promote User of a Customer to a Power User. Relation must exists.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": true,
                "version": {
                    "api": "2017-08-26 13:02:20 +0700",
                    "web": "2017-05-30 11:20:44 +0700"
                }
            }

## Admin: User Customer Power User Demote [/admin/users/{userId}/customers/{customerId}/demote]
### (Admin) User Customer Power User Demote [POST]
Demote User of a Customer from a Power User. Relation must exists.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": false,
                "version": {
                    "api": "2017-08-26 13:02:20 +0700",
                    "web": "2017-05-30 11:20:44 +0700"
                }
            }

## Group Admin: Profile
## Admin: Profile List [/admin/profiles?]
### (NOT AVAILABLE ATM) (Admin) Profile List [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 2,
                        "name": "Asset Manager (Copy)",
                        "description": "Copy of an asset manager",
                        "slug": "1-asset-manager-1",
                        "permissions": [
                            {
                                "user.create": true
                            },
                            {
                                "user.read": true
                            },
                            {
                                "user.update": true
                            }
                        ],
                        "familyProfile": {
                            "id": 1,
                            "name": "Asset Manager",
                            "slug": "asset-manager"
                        }
                    }
                ]
            }

## Group Customer: User
## Customer: User List [/customers/{customerId}/users?]
### (Customer) User List [GET]
User list for Customer. Only display accesses by given Customer.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 1,
                        "civility": "mr",
                        "lastName": "Lala",
                        "firstName": "Lulu",
                        "email": "luluz@mailinator.com",
                        "mobilePhone": null,
                        "officePhone": null,
                        "jobTitle": "CED",
                        "isAdmin": false,
                        "isActive": true,
                        "profilePicPath": null,
                        "company": {
                            "id": 1,
                            "fullName": "21 July Editz",
                            "tradeName": "1111",
                            "intercommunityVat": "11111",
                            "naf": "1111",
                            "siren": null,
                            "vat": null,
                            "vatOption": 1,
                            "raisonSociale": {
                                "id": 5,
                                "code": "M14",
                                "label": "EURL"
                            },
                            "address": {
                                "id": 1,
                                "address1": "S Las Vegas Blvd",
                                "address2": null,
                                "zipcode": "11",
                                "city": "Clark County",
                                "country": "United States",
                                "lat": 36.045999,
                                "lng": -115.1722248
                            }
                        },
                        "accesses": [
                            {
                                "id": 1,
                                "isPowerUser": true,
                                "customer": {
                                    "id": 1,
                                    "fullName": "21 July Editz",
                                    "tradeName": "1111",
                                    "vatOption": 1,
                                    "active": 0,
                                    "intercommunityVat": "11111",
                                    "vat": null,
                                    "siren": null,
                                    "naf": "1111",
                                    "iban": "FR7630001007941234567890185",
                                    "accountName": "21212",
                                    "swift": "FRFRFR76300",
                                    "addressOption": 1,
                                    "customerImg": [
                                        ""
                                    ],
                                    "company": {
                                        "id": 1,
                                        "fullName": "Tesla Corp",
                                        "tradeName": "Tesla",
                                        "intercommunityVat": "11111",
                                        "naf": "1111",
                                        "siren": null,
                                        "vat": null,
                                        "vatOption": 1,
                                        "raisonSociale": {
                                            "id": 5,
                                            "code": "M14",
                                            "label": "EURL"
                                        },
                                        "address": {
                                            "id": 1,
                                            "address1": "S Las Vegas Blvd",
                                            "address2": null,
                                            "zipcode": "11",
                                            "city": "Clark County",
                                            "country": "United States",
                                            "lat": 36.045999,
                                            "lng": -115.1722248
                                        }
                                    }
                                },
                                "resources": {
                                    "portfolios": [
                                        {
                                            "id": 1,
                                            "__DEVNOTE__id": "Id of portfolio",
                                            "profile": {
                                                "id": 3,
                                                "name": "Broker Portfolio 1",
                                                "slug": "1-broker-11231"
                                            },
                                            "allPropertiesOption": false,
                                            "properties": [
                                                {
                                                    "id": 1,
                                                    "name": "Property #1",
                                                    "__DEVNOTE_profile": "Profile here is User User Access.",
                                                    "profile": {
                                                        "id": 4,
                                                        "name": "Broker",
                                                        "slug": "1-broker-1524"
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "id": 2,
                                            "__DEVNOTE__id": "Id of portfolio",
                                            "profile": null,
                                            "allPropertiesOption": true,
                                            "__DEVNOTE_allPropertiesOption": "Property option used to override all property access.",
                                            "properties": null
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                ]
            }



## Group Customer: Profile
## Customer: Profile List [/customers/{customerId}/profiles?]
### (Customer) Profile List [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 2,
                        "name": "Asset Manager (Copy)",
                        "description": "Copy of an asset manager",
                        "slug": "1-asset-manager-1",
                        "permissions": [
                            {
                                "user.create": true
                            },
                            {
                                "user.read": true
                            },
                            {
                                "user.update": true
                            }
                        ],
                        "familyProfile": {
                            "id": 1,
                            "name": "Asset Manager",
                            "slug": "asset-manager"
                        }
                    }
                ]
            }

## Customer: Profile Detail [/customers/{customerId}/profiles/{profileId}?]
### (Customer) Profile Detail [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 2,
                    "name": "Asset Manager (Copy)",
                    "description": "Copy of an asset manager",
                    "slug": "1-asset-manager-1",
                    "permissions": [
                        {
                            "user.create": true
                        },
                        {
                            "user.read": true
                        },
                        {
                            "user.update": true
                        }
                    ],
                    
                    "familyProfile": {
                        "id": 1,
                        "name": "Asset Manager",
                        "slug": "asset-manager"
                    }
                }
            }

## Customer: Profile Create [/customers/{customerId}/profiles]
### (Customer) Profile Create [POST]

+ Request (application/json)

        {
            "name": "Asset Manager (Copy)",
            "description": "Copy of an asset manager",
        
            "__DEVNOTE__slug": "For customer, slug is generated",
            
            "permissions": [
                {
                    "user.create": true
                },
                {
                    "user.read": true
                },
                {
                    "user.update": true
                }
            ],
        
            "__DEVNOTE__familyProfile": "familyProfile can only be a `protected` & non-customer Profile",
            "familyProfile": {
                "id": 1,
                "name": "Asset Manager",
                "slug": "asset-manager"
            }
        }

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 2,
                    "name": "Asset Manager (Copy)",
                    "description": "Copy of an asset manager",
                    "slug": "1-asset-manager-1",
                    "permissions": [
                        {
                            "user.create": true
                        },
                        {
                            "user.read": true
                        },
                        {
                            "user.update": true
                        }
                    ],
                    
                    "familyProfile": {
                        "id": 1,
                        "name": "Asset Manager",
                        "slug": "asset-manager"
                    }
                }
            }

## Customer: Profile Update [/customers/{customerId}/profiles/{profileId}]
### (Customer) Profile Update [POST]

+ Request (application/json)

        {
            "id": 2,
            "name": "Asset Manager (Copy)",
            "description": "Copy of an asset manager",
        
            "__DEVNOTE__slug": "For customer, slug is auto-generated by backend.",
            
            "permissions": [
                {
                    "user.create": true
                },
                {
                    "user.read": true
                },
                {
                    "user.update": true
                }
            ],
        
            "__DEVNOTE__familyProfile": "familyProfile can only be a `protected` & non-customer Profile",
            "familyProfile": {
                "id": 1,
                "name": "Asset Manager",
                "slug": "asset-manager"
            }
        }

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 2,
                    "name": "Asset Manager (Copy)",
                    "description": "Copy of an asset manager",
                    "slug": "1-asset-manager-1",
                    "permissions": [
                        {
                            "user.create": true
                        },
                        {
                            "user.read": true
                        },
                        {
                            "user.update": true
                        }
                    ],
                    
                    "familyProfile": {
                        "id": 1,
                        "name": "Asset Manager",
                        "slug": "asset-manager"
                    }
                }
            }

## Customer: Profile List Parents [/customers/{customerId}/profiles/list?]
### (Customer) Profile Parents [GET]
List of all parents of Family Profile.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 1,
                        "name": "Asset Manager",
                        "description": "an asset manager",
                        "slug": "asset-manager",
                        "permissions": [
                            {
                                "user.create": true
                            },
                            {
                                "user.read": true
                            },
                            {
                                "user.update": true
                            }
                        ]
                    }
                ]
            }

## Customer: Profile List Child by Parent Slug [/customers/{customerId}/profiles/list/{familySlug}]
### (Customer) Profile Child by Parent Slug [GET]
List Child Profile by parent slug.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 1,
                        "name": "Asset Manager (Copy)",
                        "description": "Copy of an asset manager",
                        "slug": "asset-manager",
                        "permissions": [
                            {
                                "user.create": true
                            },
                            {
                                "user.read": true
                            },
                            {
                                "user.update": true
                            }
                        ],

                        "familyProfile": {
                            "id": 1,
                            "name": "Asset Manager",
                            "slug": "asset-manager"
                        }
                    }
                ]
            }


## Group Customer: User Access
## Customer: User Access Detail [/customers/{customerId}/users/{userId}/access?]
### (Customer) User Access Detail [GET]
As a customer, it can only see access of it's own user of the same customer detail information.
Meaning, the result here is a single object.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "portfolios": [
                        {
                            "id": 1,
                            "__DEVNOTE__id": "Id of portfolio",

                            "profile": {
                                "id": 3,
                                "name": "Broker Portfolio 1",
                                "slug": "1-broker-11231"
                            },

                            "allPropertiesOption": false,
                            "properties": [
                                {
                                    "id": 1,
                                    "name": "Property #1",

                                    "__DEVNOTE_profile": "Profile here is User User Access.",
                                    "profile": {
                                        "id": 4,
                                        "name": "Broker",
                                        "slug": "1-broker-1524"
                                    }
                                }
                            ]
                        },
                        {
                            "id": 2,
                            "__DEVNOTE__id": "Id of portfolio",

                            "profile": {
                                "id": 3,
                                "name": "Broker Portfolio General",
                                "slug": "1-broker-1141"
                            },

                            "allPropertiesOption": true,
                            "__DEVNOTE_allPropertiesOption": "Property option used to override all property access.",
                            "properties": null
                        }
                    ]
                }
            }

## Customer: User Access Update [/customers/{customerId}/users/{userId}/access]
### (Customer) User Access Update [POST]
As a customer, it can only see access of it's own user of the same customer detail information.
Will replace (deletes existing) access table content according to requested data.

+ Request (application/json)

        {
            "id": 1,
            "__DEVNOTE__id": "Id of Customer",
            "portfolios": [
                {
                    "id": 1,
                    "profile": {
                        "id": 3
                    },
                    "allPropertiesOption": false,
                    "properties": [
                        {
                            "id": 1,
                            "profile": {
                                "id": 4
                            }
                        }
                    ]
                }
            ]
        }

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "portfolios": [
                        {
                            "id": 1,
                            "__DEVNOTE__id": "Id of portfolio",

                            "profile": {
                                "id": 3,
                                "name": "Broker Portfolio 1",
                                "slug": "1-broker-11231"
                            },

                            "allPropertiesOption": false,
                            "properties": [
                                {
                                    "id": 1,
                                    "name": "Property #1",

                                    "__DEVNOTE_profile": "Profile here is User User Access.",
                                    "profile": {
                                        "id": 4,
                                        "name": "Broker",
                                        "slug": "1-broker-1524"
                                    }
                                }
                            ]
                        },
                        {
                            "id": 2,
                            "__DEVNOTE__id": "Id of portfolio",

                            "profile": {
                                "id": 3,
                                "name": "Broker Portfolio General",
                                "slug": "1-broker-1141"
                            },

                            "allPropertiesOption": true,
                            "__DEVNOTE_allPropertiesOption": "Property option used to override all property access.",
                            "properties": null
                        }
                    ]
                }
            }