eFORMAT: 1A
HOST: http://api.mv2.domain/api/v2/

# Mv2 - Web

MV2 utilizes JWT Authentication which generates token on user sign in. Token is required for most requests.
Token can be send as `token` parameter as query string or as header in such format `Authorization: Bearer {system-generated-token}`.

When sending request with body of JSON headers should contain `Content-Type: application/json`.

## Group Authentication
## Sign In [/auth/login]
### Sign In [POST]
Attempt to login and get user token.
`token` is NOT required.

+ Request (application/json)

        {
            "email": "admin@super.com",
            "password": "password"
        }

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "userType": "admin",
                    "__DEVNODE__userType": "will be `admin` or `customer`",
                    
                    "token": "your.generated.token",
                    
                    "user": {
                        "id": 1,
                        "civility": "mr",
                        "lastName": "Lala",
                        "firstName": "Lulu",
                        "email": "luluz@mailinator.com",
                        "mobilePhone": null,
                        "officePhone": null,
                        "jobTitle": "CED",
                        "isAdmin": false,
                        "isActive": true,
                        "profilePicPath": null,
                        "company": {
                            "id": 1,
                            "fullName": "21 July Editz",
                            "tradeName": "1111",
                            "intercommunityVat": "11111",
                            "naf": "1111",
                            "siren": null,
                            "vat": null,
                            "vatOption": 1,
                            "raisonSociale": {
                                "id": 5,
                                "code": "M14",
                                "label": "EURL"
                            },
                            "address": {
                                "id": 1,
                                "address1": "S Las Vegas Blvd",
                                "address2": null,
                                "zipcode": "11",
                                "city": "Clark County",
                                "country": "United States",
                                "lat": 36.045999,
                                "lng": -115.1722248
                            }
                        },

                        "accesses": [
                            {
                                "id": 1,
                                "__DEVNOTE_id": "id here is id of customer",
                                
                                "isPowerUser": 1,
                                "__DEVNOTE_userPowerLevel": "isPowerUser here is powerLevel of User per Customer",
                                
                                "customer": {
                                    "id": 1,
                                    "fullName": "21 July Editz",
                                    "tradeName": "1111",
                                    "vatOption": 1,
                                    "active": 0,
                                    "intercommunityVat": "11111",
                                    "vat": null,
                                    "siren": null,
                                    "naf": "1111",
                                    "iban": "FR7630001007941234567890185",
                                    "accountName": "21212",
                                    "swift": "FRFRFR76300",
                                    "addressOption": 1,
                                    "customerImg": [
                                        ""
                                    ],
                                    "company": {
                                        "id": 1,
                                        "fullName": "Tesla Corp",
                                        "tradeName": "Tesla",
                                        "intercommunityVat": "11111",
                                        "naf": "1111",
                                        "siren": null,
                                        "vat": null,
                                        "vatOption": 1,
                                        "raisonSociale": {
                                            "id": 5,
                                            "code": "M14",
                                            "label": "EURL"
                                        },
                                        "address": {
                                            "id": 1,
                                            "address1": "S Las Vegas Blvd",
                                            "address2": null,
                                            "zipcode": "11",
                                            "city": "Clark County",
                                            "country": "United States",
                                            "lat": 36.045999,
                                            "lng": -115.1722248
                                        }
                                    }
                                },
                                
                                "__DEVNOTE_profile": "profile is Profile used per Customer, only 1 profile per customer, per user.",
                                "profile": {
                                    "id": 1,
                                    "name": "Asset Manager",
                                    "description": "",
                                    "slug": "1-asset-manager-1",
                                    "permissions": [
                                        {
                                            "user.create": true
                                        },
                                        {
                                            "user.read": true
                                        },
                                        {
                                            "user.update": true
                                        }
                                    ],
                                    "familyProfile": {
                                        "id": 1,
                                        "name": "Asset Manager",
                                        "slug": "1-asset-manager-1"
                                    }
                                }
                            }
                        ]
                    },
                    
                }

## Sign Out [/auth/logout]
### Sign Out [POST]
Logout and clear user token.
`token` is required.

+ Request (application/json)

        {
            "email": "admin@customer.com",
        }

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": 1
            }

## Reset Password [/auth/reset-password]
### Reset Password [POST]
Reset password.

+ Request (application/json)

        {
            "email": "admin@customer.com",
        }

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "email": "admin@customer.com"
                }
            }

## Group Admin: User Resources
## Admin: User List [/admin/users?]
### (Admin) User List [GET]
User list.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 1,
                        "civility": "mr",
                        "lastName": "Lala",
                        "firstName": "Lulu",
                        "email": "luluz@mailinator.com",
                        "mobilePhone": null,
                        "officePhone": null,
                        "jobTitle": "CED",
                        "isAdmin": false,
                        "isActive": true,
                        "profilePicPath": null,
                        "company": {
                            "id": 1,
                            "fullName": "21 July Editz",
                            "tradeName": "1111",
                            "intercommunityVat": "11111",
                            "naf": "1111",
                            "siren": null,
                            "vat": null,
                            "vatOption": 1,
                            "raisonSociale": {
                                "id": 5,
                                "code": "M14",
                                "label": "EURL"
                            },
                            "address": {
                                "id": 1,
                                "address1": "S Las Vegas Blvd",
                                "address2": null,
                                "zipcode": "11",
                                "city": "Clark County",
                                "country": "United States",
                                "lat": 36.045999,
                                "lng": -115.1722248
                            }
                        },

                        "accesses": [
                            {
                                "id": 1,
                                "__DEVNOTE_id": "id here is id of customer",
                                
                                "isPowerUser": 1,
                                "__DEVNOTE_userPowerLevel": "isPowerUser here is powerLevel of User per Customer",
                                
                                "customer": {
                                    "id": 1,
                                    "fullName": "21 July Editz",
                                    "tradeName": "1111",
                                    "vatOption": 1,
                                    "active": 0,
                                    "intercommunityVat": "11111",
                                    "vat": null,
                                    "siren": null,
                                    "naf": "1111",
                                    "iban": "FR7630001007941234567890185",
                                    "accountName": "21212",
                                    "swift": "FRFRFR76300",
                                    "addressOption": 1,
                                    "customerImg": [
                                        ""
                                    ],
                                    "company": {
                                        "id": 1,
                                        "fullName": "Tesla Corp",
                                        "tradeName": "Tesla",
                                        "intercommunityVat": "11111",
                                        "naf": "1111",
                                        "siren": null,
                                        "vat": null,
                                        "vatOption": 1,
                                        "raisonSociale": {
                                            "id": 5,
                                            "code": "M14",
                                            "label": "EURL"
                                        },
                                        "address": {
                                            "id": 1,
                                            "address1": "S Las Vegas Blvd",
                                            "address2": null,
                                            "zipcode": "11",
                                            "city": "Clark County",
                                            "country": "United States",
                                            "lat": 36.045999,
                                            "lng": -115.1722248
                                        }
                                    }
                                },
                                
                                "__DEVNOTE_profile": "profile is Profile used per Customer, only 1 profile per customer, per user.",
                                "profile": {
                                    "id": 1,
                                    "name": "Asset Manager",
                                    "description": "",
                                    "slug": "1-asset-manager-1",
                                    "permissions": [
                                        {
                                            "user.create": true
                                        },
                                        {
                                            "user.read": true
                                        },
                                        {
                                            "user.update": true
                                        }
                                    ],
                                    "familyProfile": {
                                        "id": 1,
                                        "name": "Asset Manager",
                                        "slug": "1-asset-manager-1"
                                    }
                                }
                            }
                        ]
                    }
                ]
            }

## Admin: User Detail [/admin/users/{userId}?]
### (Admin) User Detail [GET]
User detail.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 1,
                    "civility": "mr",
                    "lastName": "Lala",
                    "firstName": "Lulu",
                    "email": "luluz@mailinator.com",
                    "mobilePhone": null,
                    "officePhone": null,
                    "jobTitle": "CED",
                    "isAdmin": false,
                    "isActive": true,
                    "profilePicPath": null,
                    "company": {
                        "id": 1,
                        "fullName": "21 July Editz",
                        "tradeName": "1111",
                        "intercommunityVat": "11111",
                        "naf": "1111",
                        "siren": null,
                        "vat": null,
                        "vatOption": 1,
                        "raisonSociale": {
                            "id": 5,
                            "code": "M14",
                            "label": "EURL"
                        },
                        "address": {
                            "id": 1,
                            "address1": "S Las Vegas Blvd",
                            "address2": null,
                            "zipcode": "11",
                            "city": "Clark County",
                            "country": "United States",
                            "lat": 36.045999,
                            "lng": -115.1722248
                        }
                    },

                    "accesses": [
                        {
                            "id": 1,
                            "__DEVNOTE_id": "id here is id of customer",
                            
                            "isPowerUser": 1,
                            "__DEVNOTE_userPowerLevel": "isPowerUser here is powerLevel of User per Customer",
                            
                            "customer": {
                                "id": 1,
                                "fullName": "21 July Editz",
                                "tradeName": "1111",
                                "vatOption": 1,
                                "active": 0,
                                "intercommunityVat": "11111",
                                "vat": null,
                                "siren": null,
                                "naf": "1111",
                                "iban": "FR7630001007941234567890185",
                                "accountName": "21212",
                                "swift": "FRFRFR76300",
                                "addressOption": 1,
                                "customerImg": [
                                    ""
                                ],
                                "company": {
                                    "id": 1,
                                    "fullName": "Tesla Corp",
                                    "tradeName": "Tesla",
                                    "intercommunityVat": "11111",
                                    "naf": "1111",
                                    "siren": null,
                                    "vat": null,
                                    "vatOption": 1,
                                    "raisonSociale": {
                                        "id": 5,
                                        "code": "M14",
                                        "label": "EURL"
                                    },
                                    "address": {
                                        "id": 1,
                                        "address1": "S Las Vegas Blvd",
                                        "address2": null,
                                        "zipcode": "11",
                                        "city": "Clark County",
                                        "country": "United States",
                                        "lat": 36.045999,
                                        "lng": -115.1722248
                                    }
                                }
                            },
                            
                            "__DEVNOTE_profile": "profile is Profile used per Customer, only 1 profile per customer, per user.",
                            "profile": {
                                "id": 1,
                                "name": "Asset Manager",
                                "description": "",
                                "slug": "1-asset-manager-1",
                                "permissions": [
                                    {
                                        "user.create": true
                                    },
                                    {
                                        "user.read": true
                                    },
                                    {
                                        "user.update": true
                                    }
                                ],
                                "familyProfile": {
                                    "id": 1,
                                    "name": "Asset Manager",
                                    "slug": "1-asset-manager-1"
                                }
                            }
                        }
                    ]
                }
            }

## Admin: User Create [/admin/users]
### (Admin) User Create [POST]
Create user.

+ Request (application/json)

        {
            "civility": "mr",
            "lastName": "Lala",
            "firstName": "Lulu",
            "email": "luluz@mailinator.com",
            "mobilePhone": null,
            "officePhone": null,
            "jobTitle": "CED",
        
        
            "profilePicPath": null,
        
            "__DEVNOTE__company": "Can lookup or create",
            "company": {
                "id": 1,
                "fullName": "21 July Editz",
                "tradeName": "1111",
                "raisonSociale": {
                    "id": 5,
                    "code": "M14",
                    "label": "EURL"
                },
                "intercommunityVat": "11111",
                "naf": "1111",
                "siren": null,
                "vat": null,
                "vatOption": 1,
                "address": {
                    "id": 1,
                    "address1": "S Las Vegas Blvd",
                    "address2": null,
                    "zipcode": "11",
                    "city": "Clark County",
                    "country": "United States",
                    "lat": 36.045999,
                    "lng": -115.1722248
                }
            },
        
            "accesses": [
                {
                    "id": 1,
                    "__DEVNOTE_id": "id here is id of customer",
                    
                    "isPowerUser": 1,
                    "__DEVNOTE_userPowerLevel": "isPowerUser here is powerLevel of User per Customer",
                    
                    "customer": {
                        "id": 1,
                        "fullName": "21 July Editz",
                        "tradeName": "1111",
                        "vatOption": 1,
                        "active": 0,
                        "intercommunityVat": "11111",
                        "vat": null,
                        "siren": null,
                        "naf": "1111",
                        "iban": "FR7630001007941234567890185",
                        "accountName": "21212",
                        "swift": "FRFRFR76300",
                        "addressOption": 1,
                        "customerImg": [
                            ""
                        ],
                        "company": {
                            "id": 1,
                            "fullName": "Tesla Corp",
                            "tradeName": "Tesla",
                            "intercommunityVat": "11111",
                            "naf": "1111",
                            "siren": null,
                            "vat": null,
                            "vatOption": 1,
                            "raisonSociale": {
                                "id": 5,
                                "code": "M14",
                                "label": "EURL"
                            },
                            "address": {
                                "id": 1,
                                "address1": "S Las Vegas Blvd",
                                "address2": null,
                                "zipcode": "11",
                                "city": "Clark County",
                                "country": "United States",
                                "lat": 36.045999,
                                "lng": -115.1722248
                            }
                        }
                    },
                    
                    "__DEVNOTE_profile": "profile is Profile used per Customer, only 1 profile per customer, per user.",
                    "profile": {
                        "id": 1,
                        "name": "Asset Manager",
                        "description": "an asset manager",
                        "slug": "1-asset-manager-1",
                        "permissions": [
                            {
                                "user.create": true
                            },
                            {
                                "user.read": true
                            },
                            {
                                "user.update": true
                            }
                        ],
                        "familyProfile": {
                            "id": 1,
                            "name": "Asset Manager",
                            "slug": "1-asset-manager-1"
                        }
                    }
                }
            ]
        }

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 1,
                    "civility": "mr",
                    "lastName": "Lala",
                    "firstName": "Lulu",
                    "email": "luluz@mailinator.com",
                    "mobilePhone": null,
                    "officePhone": null,
                    "jobTitle": "CED",
                    "isAdmin": false,
                    "isActive": true,
                    "profilePicPath": null,
                    "company": {
                        "id": 1,
                        "fullName": "21 July Editz",
                        "tradeName": "1111",
                        "intercommunityVat": "11111",
                        "naf": "1111",
                        "siren": null,
                        "vat": null,
                        "vatOption": 1,
                        "raisonSociale": {
                            "id": 5,
                            "code": "M14",
                            "label": "EURL"
                        },
                        "address": {
                            "id": 1,
                            "address1": "S Las Vegas Blvd",
                            "address2": null,
                            "zipcode": "11",
                            "city": "Clark County",
                            "country": "United States",
                            "lat": 36.045999,
                            "lng": -115.1722248
                        }
                    },

                    "accesses": [
                        {
                            "id": 1,
                            "__DEVNOTE_id": "id here is id of customer",
                            
                            "isPowerUser": 1,
                            "__DEVNOTE_userPowerLevel": "isPowerUser here is powerLevel of User per Customer",
                            
                            "customer": {
                                "id": 1,
                                "fullName": "21 July Editz",
                                "tradeName": "1111",
                                "vatOption": 1,
                                "active": 0,
                                "intercommunityVat": "11111",
                                "vat": null,
                                "siren": null,
                                "naf": "1111",
                                "iban": "FR7630001007941234567890185",
                                "accountName": "21212",
                                "swift": "FRFRFR76300",
                                "addressOption": 1,
                                "customerImg": [
                                    ""
                                ],
                                "company": {
                                    "id": 1,
                                    "fullName": "Tesla Corp",
                                    "tradeName": "Tesla",
                                    "intercommunityVat": "11111",
                                    "naf": "1111",
                                    "siren": null,
                                    "vat": null,
                                    "vatOption": 1,
                                    "raisonSociale": {
                                        "id": 5,
                                        "code": "M14",
                                        "label": "EURL"
                                    },
                                    "address": {
                                        "id": 1,
                                        "address1": "S Las Vegas Blvd",
                                        "address2": null,
                                        "zipcode": "11",
                                        "city": "Clark County",
                                        "country": "United States",
                                        "lat": 36.045999,
                                        "lng": -115.1722248
                                    }
                                }
                            },
                            
                            "__DEVNOTE_profile": "profile is Profile used per Customer, only 1 profile per customer, per user.",
                            "profile": {
                                "id": 1,
                                "name": "Asset Manager",
                                "description": "",
                                "slug": "1-asset-manager-1",
                                "permissions": [
                                    {
                                        "user.create": true
                                    },
                                    {
                                        "user.read": true
                                    },
                                    {
                                        "user.update": true
                                    }
                                ],
                                "familyProfile": {
                                    "id": 1,
                                    "name": "Asset Manager",
                                    "slug": "1-asset-manager-1"
                                }
                            }
                        }
                    ]
                }
            }
## Admin: User Update [/admin/users/{userId}]
### (Admin) User Update [POST]

+ Request (application/json)

+ Response 200 (application/json)

## Admin: User Delete [/admin/users/{userId}/delete]
### (Admin) User Delete [POST]

+ Request (application/json)

+ Response 200 (application/json)

## Admin: User Impersonate [/admin/users/{userId}/impersonate]
### (Admin) User Impersonate [POST]
Login as selected User.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "userType": "admin",
                    "__DEVNODE__userType": "will be `admin` or `customer`",
                    
                    "token": "your.generated.token",
                    
                    "user": {
                        "id": 1,
                        "civility": "mr",
                        "lastName": "Lala",
                        "firstName": "Lulu",
                        "email": "luluz@mailinator.com",
                        "mobilePhone": null,
                        "officePhone": null,
                        "jobTitle": "CED",
                        "isAdmin": false,
                        "isActive": true,
                        "profilePicPath": null,
                        "company": {
                            "id": 1,
                            "fullName": "21 July Editz",
                            "tradeName": "1111",
                            "intercommunityVat": "11111",
                            "naf": "1111",
                            "siren": null,
                            "vat": null,
                            "vatOption": 1,
                            "raisonSociale": {
                                "id": 5,
                                "code": "M14",
                                "label": "EURL"
                            },
                            "address": {
                                "id": 1,
                                "address1": "S Las Vegas Blvd",
                                "address2": null,
                                "zipcode": "11",
                                "city": "Clark County",
                                "country": "United States",
                                "lat": 36.045999,
                                "lng": -115.1722248
                            }
                        },

                        "accesses": [
                            {
                                "id": 1,
                                "__DEVNOTE_id": "id here is id of customer",
                                
                                "isPowerUser": 1,
                                "__DEVNOTE_userPowerLevel": "isPowerUser here is powerLevel of User per Customer",
                                
                                "customer": {
                                    "id": 1,
                                    "fullName": "21 July Editz",
                                    "tradeName": "1111",
                                    "vatOption": 1,
                                    "active": 0,
                                    "intercommunityVat": "11111",
                                    "vat": null,
                                    "siren": null,
                                    "naf": "1111",
                                    "iban": "FR7630001007941234567890185",
                                    "accountName": "21212",
                                    "swift": "FRFRFR76300",
                                    "addressOption": 1,
                                    "customerImg": [
                                        ""
                                    ],
                                    "company": {
                                        "id": 1,
                                        "fullName": "Tesla Corp",
                                        "tradeName": "Tesla",
                                        "intercommunityVat": "11111",
                                        "naf": "1111",
                                        "siren": null,
                                        "vat": null,
                                        "vatOption": 1,
                                        "raisonSociale": {
                                            "id": 5,
                                            "code": "M14",
                                            "label": "EURL"
                                        },
                                        "address": {
                                            "id": 1,
                                            "address1": "S Las Vegas Blvd",
                                            "address2": null,
                                            "zipcode": "11",
                                            "city": "Clark County",
                                            "country": "United States",
                                            "lat": 36.045999,
                                            "lng": -115.1722248
                                        }
                                    }
                                },
                                
                                "__DEVNOTE_profile": "profile is Profile used per Customer, only 1 profile per customer, per user.",
                                "profile": {
                                    "id": 1,
                                    "name": "Asset Manager",
                                    "description": "",
                                    "slug": "1-asset-manager-1",
                                    "permissions": [
                                        {
                                            "user.create": true
                                        },
                                        {
                                            "user.read": true
                                        },
                                        {
                                            "user.update": true
                                        }
                                    ],
                                    "familyProfile": {
                                        "id": 1,
                                        "name": "Asset Manager",
                                        "slug": "1-asset-manager-1"
                                    }
                                }
                            }
                        ]
                    },
                    
                }

## Admin: User Toggle Active [/admin/users/{userId}/toggle-active]
### (Admin) User Toggle Active [POST]
Toggle User Active Status.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "User Detail"
            }

## Admin: User Toggle Power User [/admin/users/{userId}/toggle-power-user]
### (Admin) User Toggle Power User [POST]
Toggle User Power User Status. Will be available on user with Company registered with valid Customer.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "User Detail"
            }

## Admin: User Reset Password [/admin/users/{userId}/reset-password]
### (Admin) User Reset Password [POST]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "User Detail"
            }

## Group Admin: Profile Resources
## Admin: Profile List [/admin/profiles?]
### (Admin) Profile List [GET]

+ Request (application/json)

+ Response 200 (application/json)

## Group Customer: Profile Resources
## Customer: Profile List [/customers/{customerId}/profiles?]
### (Customer) Profile List [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 2,
                        "name": "Asset Manager (Copy)",
                        "description": "Copy of an asset manager",
                        "slug": "1-asset-manager-1",
                        "permissions": [
                            {
                                "user.create": true
                            },
                            {
                                "user.read": true
                            },
                            {
                                "user.update": true
                            }
                        ],
                        "familyProfile": {
                            "id": 1,
                            "name": "Asset Manager",
                            "slug": "asset-manager"
                        }
                    }
                ]
            }

## Customer: Profile Detail [/customers/{customerId}/profiles/{profileId}?]
### (Customer) Profile Detail [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 2,
                    "name": "Asset Manager (Copy)",
                    "description": "Copy of an asset manager",
                    "slug": "1-asset-manager-1",
                    "permissions": [
                        {
                            "user.create": true
                        },
                        {
                            "user.read": true
                        },
                        {
                            "user.update": true
                        }
                    ],
                    
                    "familyProfile": {
                        "id": 1,
                        "name": "Asset Manager",
                        "slug": "asset-manager"
                    }
                }
            }

## Customer: Profile Create [/customers/{customerId}/profiles]
### (Customer) Profile Create [POST]

+ Request (application/json)

        {
            "name": "Asset Manager (Copy)",
            "description": "Copy of an asset manager",
        
            "__DEVNOTE__slug": "For customer, slug is generated",
            
            "permissions": [
                {
                    "user.create": true
                },
                {
                    "user.read": true
                },
                {
                    "user.update": true
                }
            ],
        
            "__DEVNOTE__familyProfile": "familyProfile can only be a `protected` & non-customer Profile",
            "familyProfile": {
                "id": 1,
                "name": "Asset Manager",
                "slug": "asset-manager"
            }
        }

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": {
                    "id": 2
                }
            }

## Customer: Profile Update [/customers/{customerId}/profiles/{profileId}]
### (Customer) Profile Update [POST]

+ Request (application/json)

+ Response 200 (application/json)

## Customer: Profile List Parents [/customers/{customerId}/profiles/list?]
### (Customer) Profile Parents [GET]
List of all parents of Family Profile.

+ Request (application/json)

+ Response 200 (application/json)

    + Body
        
            {
                "code": 0,
                "message": "Success",
                "data": [
                    {
                        "id": 1,
                        "name": "Asset Manager",
                        "description": "an asset manager",
                        "slug": "asset-manager",
                        "permissions": [
                            {
                                "user.create": true
                            },
                            {
                                "user.read": true
                            },
                            {
                                "user.update": true
                            }
                        ]
                    }
                ]
            }

## Customer: Profile List Child by Parent Slug [/customers/{customerId}/profiles/list/{profileSlug}]
### (Customer) Profile Child by Parent Slug [GET]
List Child Profile by parent slug.

+ Request (application/json)

+ Response 200 (application/json)


## Group Customer: User Access Resources
## Customer: User Access List [/customers/{customerId}/users/{userId}/accesses?]
### (Customer) User Access List [GET]

+ Request (application/json)

+ Response 200 (application/json)

    + Body
    
            {
                "accesses": [
                    {
                        "id": 1,
                        "isPowerUser": true,
                        "profileData": {
                            "id": 1,
                            "name": "Asset Manager",
                            "description": "",
                            "slug": "1-asset-manager-1",
                            "permissions": [
                                {
                                    "user.create": true
                                },
                                {
                                    "user.read": true
                                },
                                {
                                    "user.update": true
                                }
                            ],
                            "familyProfile": {
                                "id": 1,
                                "name": "Asset Manager",
                                "slug": "1-asset-manager-1"
                            }
                        },
            
                        "resources": {
                            "portfoliosOption": true,
                            "__DEVNOTE__portfoliosOption": "Is optional value to override all portfolio selection.",
            
                            "portfolios": [
                                {
                                    "id": 1,
                                    "__DEVNOTE__id": "ID of Portfolio",
            
                                    "familyProfile": {
                                        "id": 3,
                                        "slug": "broker"
                                    },
            
                                    "propertiesOption": true,
                                    "__DEVNOTE__propertiesOption": "Is optional value to override all portfolio selection.",
            
                                    "properties": [
                                        {
                                            "id": 1,
            
                                            "familyProfile": {
                                                "id": 3,
                                                "slug": "broker"
                                            }
                                        },
                                        {
                                            "id": 2,
            
                                            "familyProfile": null
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                ]
            }